// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";

// Session-mode pooler (port 5432) — used for migrations and db push
const sessionUrl = process.env["DIRECT_URL"]!;

const pool = new Pool({
  connectionString: sessionUrl,
  ssl: { rejectUnauthorized: false },
});

const adapter = new PrismaPg(pool);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: sessionUrl,
    adapter,
  },
});
